"""Generate numeric completion metadata; no runtime database dependency.

Usage: python scripts/generate_quest_requirements.py [--source classic.sql.gz]
The pinned Classic snapshot is intentionally conservative about scripted quests.
"""
import argparse
import csv
import gzip
import hashlib
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REVISION = 'ec4f596146be6467ea93c57397858e329e2db852'
URL = f'https://raw.githubusercontent.com/cmangos/classic-db/{REVISION}/Full_DB/ClassicDB_1_12_1_z2815.sql.gz'
SHA256 = '4f92db520868ab4e566726f68b5b2e380ae781209beaf22237b4f7f04600d0c0'
ROW = re.compile(r"\((?:'(?:\\.|''|[^'\\])*'|[^()'])*\)")


def extract(blob):
    if hashlib.sha256(blob).hexdigest() != SHA256:
        raise ValueError('Source does not match the pinned database snapshot')
    sql = gzip.decompress(blob).decode('utf-8')
    schema = re.search(r'CREATE TABLE `quest_template` \((.*?)\) ENGINE=', sql, re.S)[1]
    columns = re.findall(r'^  `([^`]+)`', schema, re.M)
    supported = set(map(int, re.findall(r'\[(\d+)\]', (ROOT / 'quest_xp_data.lua').read_text())))
    records = {}
    for line in sql.splitlines():
        if not line.startswith('INSERT INTO `quest_template` VALUES '):
            continue
        for match in ROW.finditer(line):
            values = next(csv.reader([match[0][1:-1]], quotechar="'", escapechar='\\'))
            if len(values) != len(columns):
                raise ValueError('Unexpected quest row shape')
            row = dict(zip(columns, values))
            quest_id = int(row['entry'])
            if quest_id not in supported:
                continue
            number = lambda key: int(row[key])
            money = max(0, -number('RewOrReqMoney'))
            count = sum(number(f'ReqItemId{i}') != 0 for i in range(1, 5))
            count += sum(number(f'ReqCreatureOrGOId{i}') != 0 or number(f'ReqSpellCast{i}') != 0
                         for i in range(1, 5))
            special = (number('SpecialFlags') & ~1 or number('LimitTime')
                       or number('StartScript') or number('RequiredCondition')
                       or number('RepObjectiveFaction') or row['EndText']
                       or any(number(f'ReqSourceId{i}') for i in range(1, 5)))
            # 0: require authoritative completion; 1: turn-in only; 2: counted objectives.
            mode = 0 if special else 2 if count else 1
            records[quest_id] = (mode, money, count)
    if len(records) < 3000:
        raise ValueError('Unexpectedly small Classic quest dataset')
    return records


def render(records):
    lines = ['-- Generated by scripts/generate_quest_requirements.py; see THIRD_PARTY.md.',
             '-- {mode: 0=native-only, 1=turn-in-only, 2=objectives, required copper, objective count}',
             'XPTrackerProQuestRequirements = {']
    lines += [f'    [{key}] = {{{mode}, {money}, {count}}},'
              for key, (mode, money, count) in sorted(records.items())]
    return '\n'.join(lines + ['}', ''])


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    blob = args.source.read_bytes() if args.source else urllib.request.urlopen(URL).read()
    records = extract(blob)
    text = render(records)
    target = ROOT / 'quest_requirements.lua'
    if args.check:
        assert target.read_text(encoding='utf-8') == text, 'Generated metadata is stale'
    else:
        target.write_text(text, encoding='utf-8', newline='\n')
    print(f'PASS: {len(records)} quests; {sum(r[0] == 1 for r in records.values())} turn-in-only quests')
